# Generated by Django 4.1.6 on 2023-02-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='awards',
            field=models.ManyToManyField(to='main_app.award'),
        ),
    ]
